# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python.
[NumPy User Guide](https://docs.scipy.org/doc/numpy/user/index.html)

### **importing numpy**

In [64]:
import numpy as np

###  **creat an array** --> **np.array()**

In [65]:
lst_1=[1,2,3,4,5,6]

np.array(lst_1)

array([1, 2, 3, 4, 5, 6])

In [66]:
mat_1=[[1,2,3],[4,5,6],[7,8,9]]

np.array(mat_1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### **np.arange(low,high,step)**

In [67]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

### **np.zeros(n)** --> **1d**
**np.zeros((m,n))** --> **2d**

In [68]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### **np.ones(n)** --> **1D**
**np.ones((m,n))** --> **2D**

In [69]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### **np.eye(n)**

In [70]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **np.random.rand(n)** :random uniform distribution over ``[0, 1)``
**np.random.rand(m,n)** --> 2D

In [71]:
np.random.rand(5)

array([0.71536376, 0.80422581, 0.617325  , 0.83736432, 0.48533353])

### **np.random.randn(n)** :"standard normal" distribution over ``0``
**np.random.randn(m,n)** --> 2D

In [72]:
np.random.randn(3,3)

array([[-1.26671631, -0.26695091, -0.77554198],
       [-0.2451118 ,  0.78198602, -0.71329139],
       [ 1.19769041, -0.42270806,  0.15604956]])

### **np.random.randint(low,high,size)** random integers in [low,high)

In [73]:
np.random.randint(10,20,5)

array([14, 17, 18, 11, 17])

### np.linspace(start,stop,num)

In [216]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

### **array.reshape(m,n)**

In [74]:
arr_1= np.arange(16)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [75]:
arr_1.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Methodes: max() , min() , argmax() , argmin() , sum , mean() , std()

In [76]:
arr_2=np.random.randint(20,80,15).reshape(3,5)
arr_2

array([[70, 77, 37, 36, 60],
       [77, 56, 70, 79, 40],
       [59, 74, 46, 41, 32]])

In [77]:
arr_2.max()

79

In [78]:
arr_2.min()

32

In [79]:
arr_2.argmax()

8

In [96]:
arr_2.argmin()

14

In [98]:
arr_2.mean()

56.93333333333333

### dot() :Dot product of two arrays

In [104]:
x=np.array([1,2,3])
y=np.array([10,20,30])

x.dot(y)

140

### Attributes: shape , ndim , size , dtype

In [85]:
arr_2.shape

(3, 5)

In [86]:
arr_2.ndim

2

In [87]:
arr_2.size

15

In [88]:
arr_2.dtype

dtype('int64')

### Indexing and Broadcasting

In [91]:
arr_3= np.arange(11)
arr_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr_3[4]

4

In [93]:
arr_3[2:5]

array([2, 3, 4])

In [95]:
arr_3[6::-1]

array([6, 5, 4, 3, 2, 1, 0])

In [106]:
arr_3[:5]=100
arr_3

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### Slicing: No Copy at All
Slicing an array returns a view of it.

In [117]:
arr_4=np.arange(10)
arr_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
arr_4_slice= arr_4[:5]
arr_4_slice

array([0, 1, 2, 3, 4])

In [119]:
arr_4_slice[:]=50
arr_4_slice

array([50, 50, 50, 50, 50])

In [120]:
arr_4

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9])

### copy()
Data is copied, it's not a view anymore.

In [122]:
arr_copy= arr_2.copy()
arr_copy

array([[70, 77, 37, 36, 60],
       [77, 56, 70, 79, 40],
       [59, 74, 46, 41, 32]])

### 2D Indexing and Fancy Indexing

<img style="float: left;" src= 'https://i.stack.imgur.com/Q3kpa.png' />

In [129]:
arr_5= np.arange(25).reshape(5,5)
arr_5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [131]:
arr_5[2][3]

13

In [132]:
arr_5[2,3]

13

In [135]:
#arr_5[1][:]
#arr_5[1,:]
arr_5[1]

array([5, 6, 7, 8, 9])

In [128]:
arr_5[:,2]

array([ 2,  7, 12, 17, 22])

In [211]:
arr_5[3:,1:4]

array([[16, 17, 18],
       [21, 22, 23]])

In [214]:
#note the difference
arr_5[2,3:]

array([13, 14])

In [213]:
arr_5[2:3,3:]

array([[13, 14]])

In [150]:
arr2d= np.zeros((7,10))
arr_row_len= arr2d.shape[0]
#arr_row_len= arr2d[1].size
for i in range(arr_row_len):
    arr2d[i]=i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [156]:
arr2d[[6,2,4]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [167]:
arr2d[:,[0,2,4]]

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.]])

In [170]:
arr2d[2:6,[0,2,4]]

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.]])

In [191]:
arr_6=np.arange(36).reshape(6,6)
arr_6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [192]:
arr_6[[5,3,1],[0,2,4]]

array([30, 20, 10])

In [193]:
arr_6[:,::-1]

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24],
       [35, 34, 33, 32, 31, 30]])

### Selection

In [194]:
arr_6[arr_6 > 21]

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

### Arithmetic

In [196]:
arr_7 = np.arange(10)
arr_7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
arr_7 +arr_7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [201]:
arr_7 -arr_7

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [202]:
arr_7 *arr_7

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [204]:
arr_7 /arr_7

/home/siavash/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [205]:
1 /arr_7

/home/siavash/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [206]:
arr_7**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [207]:
arr_7**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

### Universal Array Functions
[scipy ufunc](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)

**Math operations: exp(), log(), log2(), log10(), sqrt(), gcd(), lcm(), ...**

**Trigonometric functions: sin(), cos(), tan(), deg2rad(), rad2deg(), ...**

In [208]:
np.sin(arr_7)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [209]:
np.log10(arr_7)

/home/siavash/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])